###########
# ENV VARS:
# - DOCKER_USERNAME
# - DOCKER_PASSWORD
# - GITHUB_TOKEN (default)
###########

name: Publish Docker Image

on:
  push:
    paths:
      - 'release-versions/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Get current repository
        uses: actions/checkout@v5

      - name: Get the version
        id: vars
        run: echo "tag=$(cat release-versions/strapi-latest.txt)" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build (default => debian)
        uses: docker/build-push-action@v6
        with:
          context: ./images/strapi-debian
          build-args: |
            STRAPI_VERSION=${{steps.vars.outputs.tag}}
            NODE_VERSION=22
          # platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/strapi:${{ steps.vars.outputs.tag }}
            ${{ secrets.DOCKER_USERNAME }}/strapi:latest

      - name: Build (alpine)
        uses: docker/build-push-action@v6
        with:
          context: ./images/strapi-alpine
          build-args: |
            STRAPI_VERSION=${{ steps.vars.outputs.tag }}
            NODE_VERSION=22
          # platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/strapi:${{ steps.vars.outputs.tag }}-alpine
            ${{ secrets.DOCKER_USERNAME }}/strapi:latest-alpine

      - name: Docker Hub Description (README.md)
        uses: peter-evans/dockerhub-description@v5
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: sh1su/strapi
          readme-filepath: README.md

      - name: Create Release in GitHub
        id: create_release
        uses: softprops/action-gh-release@v2
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: v${{steps.vars.outputs.tag}}
          name: Release ${{steps.vars.outputs.tag}}
          body: strapi v${{steps.vars.outputs.tag}}
